# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_data_struct.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18sensor_data_struct.proto\x12\x12sensor_data_struct\"\xc0\x01\n\tLidarScan\x12\x11\n\tangle_min\x18\x01 \x01(\x02\x12\x11\n\tangle_max\x18\x02 \x01(\x02\x12\x17\n\x0f\x61ngle_increment\x18\x03 \x01(\x02\x12\x16\n\x0etime_increment\x18\x04 \x01(\x02\x12\x11\n\tscan_time\x18\x05 \x01(\x02\x12\x11\n\trange_min\x18\x06 \x01(\x02\x12\x11\n\trange_max\x18\x07 \x01(\x02\x12\x0e\n\x06ranges\x18\x08 \x03(\x02\x12\x13\n\x0bintensities\x18\t \x03(\x02\"<\n\x07IMUData\x12\x17\n\x0flinear_velocity\x18\x01 \x03(\x02\x12\x18\n\x10\x61ngular_velocity\x18\x02 \x03(\x02\"6\n\x0cOdometryData\x12\x0c\n\x04pose\x18\x01 \x03(\x02\x12\x18\n\x10wheel_velocities\x18\x02 \x03(\x02\"\x9e\x01\n\x10SensorDataStruct\x12(\n\x03imu\x18\x01 \x01(\x0b\x32\x1b.sensor_data_struct.IMUData\x12\x32\n\x08odometry\x18\x02 \x01(\x0b\x32 .sensor_data_struct.OdometryData\x12,\n\x05lidar\x18\x03 \x01(\x0b\x32\x1d.sensor_data_struct.LidarScanb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_data_struct_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIDARSCAN._serialized_start=49
  _LIDARSCAN._serialized_end=241
  _IMUDATA._serialized_start=243
  _IMUDATA._serialized_end=303
  _ODOMETRYDATA._serialized_start=305
  _ODOMETRYDATA._serialized_end=359
  _SENSORDATASTRUCT._serialized_start=362
  _SENSORDATASTRUCT._serialized_end=520
# @@protoc_insertion_point(module_scope)
